import type { Config } from 'tailwindcss';

const config: Config = {
  content: [
    './src/pages/**/*.{js,ts,jsx,tsx,mdx}',
    './src/components/**/*.{js,ts,jsx,tsx,mdx}',
    './src/app/**/*.{js,ts,jsx,tsx,mdx}',
    './src/**/*.{js,ts,jsx,tsx,mdx}',
  ],
  theme: {
    extend: {
        colors: {
          "tertiary-fixed": "#eaddff",
          "outline-variant": "#bfc7d5",
          "surface-tint": "#0061a5",
          "surface-dim": "#d9dadb",
          "inverse-primary": "#9fcaff",
          "tertiary-container": "#a57eff",
          "surface-container-low": "#f3f4f5",
          "on-primary-fixed": "#001c37",
          "on-secondary-fixed": "#141b2c",
          "primary-fixed": "#d2e4ff",
          "secondary-fixed": "#dbe2f9",
          "tertiary-fixed-dim": "#d1bcff",
          "on-surface": "#191c1d",
          "on-primary": "#ffffff",
          "surface": "#f8f9fa",
          "on-primary-container": "#002f55",
          "on-background": "#191c1d",
          "inverse-on-surface": "#f0f1f2",
          "on-secondary-fixed-variant": "#3f4759",
          "on-tertiary": "#ffffff",
          "primary-container": "#0d99ff",
          "primary-fixed-dim": "#9fcaff",
          "surface-container-high": "#e7e8e9",
          "surface-variant": "#e1e3e4",
          "surface-container-highest": "#e1e3e4",
          "secondary": "#565e71",
          "on-secondary-container": "#5c6477",
          "inverse-surface": "#2e3132",
          "error": "#ba1a1a",
          "on-tertiary-fixed": "#24005b",
          "on-secondary": "#ffffff",
          "surface-container-lowest": "#ffffff",
          "outline": "#707884",
          "background": "#f8f9fa",
          "on-primary-fixed-variant": "#00497e",
          "error-container": "#ffdad6",
          "secondary-fixed-dim": "#bfc6dc",
          "on-tertiary-fixed-variant": "#5425ac",
          "on-surface-variant": "#3f4753",
          "surface-bright": "#f8f9fa",
          "surface-container": "#edeeef",
          "secondary-container": "#dbe2f9",
          "tertiary": "#6d43c6",
          "on-error-container": "#93000a",
          "on-tertiary-container": "#3a008a",
          "primary": "#0061a5",
          "on-error": "#ffffff",
          obsidian: {
            950: '#070709',
            900: '#0e0e12',
            850: '#14141a',
            800: '#1b1b22',
            700: '#282832',
          },
          gold: {
            50: '#fffbeb',
            100: '#fef3c7',
            200: '#fde68a',
            300: '#fcd34d',
            400: '#fbbf24',
            500: '#d4af37',
            600: '#b48e26',
            700: '#8d6c17',
            800: '#6a5113',
            900: '#48370e',
          },
        },
      fontFamily: {
        sans: ['Inter', 'sans-serif'],
        display: ['Outfit', 'sans-serif'],
        mono: ['JetBrains Mono', 'monospace'],
      },
      boxShadow: {
        'gold-glow': '0 0 25px rgba(212, 175, 55, 0.25)',
        'gold-glow-lg': '0 0 40px rgba(212, 175, 55, 0.35)',
      },
    },
  },
  plugins: [],
};

export default config;
